### ISSUE TITLE
Bug: Your Titlecan't concat Picture to bytes

### ISSUE THREAD

**Issue by alternistom** [nathom/streamrip#155] opened 2021-08-17 10:56 UTC
## Bug Report

**Current Behavior**
```bash
TypeError████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████   | 00:00 left at 1.61MB/s

  can't concat Picture to bytes

  at c:\users\alternistom\appdata\local\programs\python\python38\lib\site-packages\mutagen\mp4\__init__.py:789 in __render_cover
       785│                 imageformat = cover.imageformat
       786│             except AttributeError:
       787│                 imageformat = MP4Cover.FORMAT_JPEG
       788│             atom_data.append(Atom.render(
    →  789│                 b"data", struct.pack(">2I", imageformat, 0) + cover))
       790│         return Atom.render(_key2name(key), b"".join(atom_data))
       791│
       792│     def __parse_text(self, atom, data, implicit=True):
       793│         # implicit = False, for parsing unknown atoms only take utf8 ones.

If this was unexpected, please open a Bug Report at https://github.com/nathom/streamrip/issues/new/choose
```

**Command used:**

```bash
# rip url https://listen.tidal.com/album/9638833
```

**Expected behavior**

**`streamrip` Configuration File (find using `rip config -o`):**
original, did not change anything

**Environment**

- `streamrip` version(s): 1.3
- Python version: 3.8
- OS: Win10

**Possible Solution**
UTF-8?

**Comment by nathom** [comment] 2021-08-18 14:43
Can you reproduce this? If so, append `-vvv` to the command and paste the output here.

**Comment by nathom** [comment] 2021-09-12 16:05
Closing because @alternistom isn't responding.

**Closed by nathom** 2021-09-12 16:05 UTC
Labels: bug
