### ISSUE TITLE
Bug: Doesn't download all albums by artist using artist id

### ISSUE THREAD

**Issue by Gamer4Life2020** [nathom/streamrip#126] opened 2021-07-27 18:23 UTC
## Bug Report

**Current Behavior**
Doesn't download all albums by artist using artist id, but can separately. 

**Command used:**
rip -u

```bash
rip -u https://open.qobuz.com/artist/147414
```

**Expected behavior**
Most of the time when downloading an artist id, it will download fine without issue unless unavailable.
Normally I have these on but turned off and no change.

```toml
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove albums whose artist is not the one requested
features = false

# Paste the contents of config.toml here
# REMOVE YOUR CREDENTIALS
[downloads]
# Folder where tracks are downloaded to
folder = "F:\\Music DL"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = true
# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
concurrent = true


[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 4
# This will download booklet pdfs that are included with some albums
download_booklets = false

email = ""
# This is an md5 hash of the plaintext password
password = ""
# Do not change
app_id = ""
# Do not change
secrets = []


[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = ""
country_code = ""
access_token = ""
refresh_token = ""
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = ""

# Doesn't require login

[deezer]
# 0, 1, or 2
quality = 2


[soundcloud]
# Only 0 is available for now
quality = 0


[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = ""

# This stores a list of item IDs so that repeats are not downloaded.

[database.downloads]
enabled = true
path = "C:\\Users\\User\\AppData\\Roaming\\streamrip\\downloads.db"

# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads

[database.failed_downloads]
enabled = true
path = "C:\\Users\\User\\AppData\\Roaming\\streamrip\\failed_downloads.db"

# Convert tracks to a codec after downloading them.

[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.

[filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false


[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
size = "large"
# Both of these options limit the size of the embedded artwork. If their values
# are larger than the actual dimensions of the image, they will be ignored.
max_width = 999999
max_height = 999999
# Save the cover image at the highest quality as a seperate jpg file
keep_hires_cover = true


[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# Replaces the original track's tracknumber with it's position in the playlist
new_playlist_tracknumbers = true

# Changes the folder and file names generated by streamrip.

[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "container", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer"
track_format = "{tracknumber}. {artist} - {title}"

# Last.fm playlists are downloaded by searching for the titles of the tracks

[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = "deezer"


[misc]
# Check whether a newer version of streamrip is available when starting up
check_for_updates = true

# Metadata to identify this config file. Do not change.
version = "0.7.1"

```

**Environment**

- `streamrip` version(s): [e.g. v0.7.1]
- Python version: [e.g. 3.9]
- OS: [Windows 10]

**Comment by nathom** [comment] 2021-07-29 00:06
I can't reproduce it on the current `dev` branch. Maybe I accidentally fixed it :). You can try it out now or wait until the `0.8` release to see if the issue is gone.

**Comment by Gamer4Life2020** [comment] 2021-07-29 14:28
Ok, thanks. I guess I'm special as I can't seem to get the Dev to work. I have downloaded the zip and it was missing the rip.exe so not sure what .py file to use/run. I even tried to copy the files over the 7.1 once no luck. I don't mind waiting until the next release, I don't like not having to make a playlist or copy every album into a txt but can't complain for free. Thanks again.

**Comment by nathom** [comment] 2021-07-31 04:44
This should be fixed in `v1.0`. Please let me know if you still have the issue.

**Comment by Gamer4Life2020** [comment] 2021-08-01 20:47
Not a big deal as I check manually after all downloads, but the issue is still there in 1.1 so not sure if it's a link or region issue.
As, so far it's the only artist I have had this issue with. If doing separate links it's fine.
![Not dling all albums per artist id](https://user-images.githubusercontent.com/36717721/127784871-ccd766a2-346a-4927-a4d2-f89ceb507c96.PNG)
------------------------------------------------
[downloads]
# Folder where tracks are downloaded to
folder = "F:\\Music DL"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = true



[downloads.concurrency]
# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
enabled = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
max_connections = 2



[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 4
# This will download booklet pdfs that are included with some albums
download_booklets = true

email = ""
# This is an md5 hash of the plaintext password
password = ""
# Do not change
app_id = ""
# Do not change
secrets = [""]



[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = false

# Do not change any of the fields below
user_id = ""
country_code = ""
access_token = ""
refresh_token = ""
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = ""



[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See [ADD LINK] for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true



[soundcloud]
# Only 0 is available for now
quality = 0



[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = ""

# This stores a list of item IDs so that repeats are not downloaded.


[database.downloads]
enabled = false
path = "C:\\Users\\MASTER\\AppData\\Local\\streamrip\\streamrip\\downloads.db"

# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads


[database.failed_downloads]
enabled = true
path = "C:\\Users\\MASTER\\AppData\\Local\\streamrip\\streamrip\\failed_downloads.db"

# Convert tracks to a codec after downloading them.


[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.


[filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = true
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = true
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false



[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
size = "large"
# Both of these options limit the size of the embedded artwork. If their values
# are larger than the actual dimensions of the image, they will be ignored.
max_width = 999999
max_height = 999999
# Save the cover image at the highest quality as a seperate jpg file
keep_hires_cover = true



[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# Replaces the original track's tracknumber with it's position in the playlist
new_playlist_tracknumbers = true

# Changes the folder and file names generated by streamrip.


[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "container", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer"
track_format = "{tracknumber}. {artist} - {title}"

# Last.fm playlists are downloaded by searching for the titles of the tracks


[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = "deezer"



[theme]
# Options: "dainty" or "plain"
progress_bar = "dainty"



[misc]
# Metadata to identify this config file. Do not change.
version = "1.1"

**Comment by Gamer4Life2020** [comment] 2021-08-01 20:48
Sorry, not sure on the bold as it was just copied and pasted.

**Comment by Gamer4Life2020** [comment] 2021-08-01 21:05
Also, On this no issues if not and I can make a new issue/enhancement if need be. All the tracks not available on this for whatever reason are on the smash album, would there be anyway of searching/fallback for missing tracks if available on other albums?

**Comment by nathom** [comment] 2021-08-02 00:28
It looks like those tracks are restricted by Qobuz:
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/74019033/127790195-a564a00b-ec3c-40ab-8cb6-ad79e89addcf.png">
[Qobuz Store](https://www.qobuz.com/us-en/album/greatest-hits-the-offspring/0060255727099)
There's no way to download them.

**Closed** 2021-08-02 18:42 UTC
Labels: bug
