### ISSUE TITLE
Bug: TypeError: can't concat Picture to bytes

### ISSUE THREAD

**Issue by zzzzzozzzzz** [nathom/streamrip#87] opened 2021-05-30 14:49 UTC
## Bug Report
**Source**
Tidal

**Command used:**

```bash
rip -u 'link'
```

**`streamrip` Configuration File (extracts):**

```yaml
tidal:
  quality: 1
```
```yaml
conversion:
  enabled: false
```
```yaml
artwork:
  embed: true
  size: large
  keep_hires_cover: true
```

**Environment**

- `streamrip` version: latest main
- Python version: 3.9
- OS: Linux

**Traceback**
```bash
Traceback (most recent call last):
  File "/home/user/streamripp/.venv/bin/rip", line 33, in <module>
    sys.exit(load_entry_point('streamrip', 'console_scripts', 'rip')())
  File "/home/user/streamripp/streamrip/cli.py", line 329, in main
    cli(obj={})
  File "/home/user/streamripp/.venv/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/streamripp/.venv/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/user/streamripp/.venv/lib/python3.9/site-packages/click/core.py", line 1646, in invoke
    super().invoke(ctx)
  File "/home/user/streamripp/.venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/streamripp/.venv/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/user/streamripp/.venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/user/streamripp/streamrip/cli.py", line 113, in cli
    core.download()
  File "/home/user/streamripp/streamrip/core.py", line 257, in download
    item.download(**arguments)
  File "/home/user/streamripp/streamrip/bases.py", line 866, in download
    target(item, **kwargs)
  File "/home/user/streamripp/streamrip/tracklists.py", line 204, in _download_item
    track.tag(
  File "/home/user/streamripp/streamrip/bases.py", line 531, in tag
    audio["covr"] = [cover]
  File "/home/user/streamripp/.venv/lib/python3.9/site-packages/mutagen/_file.py", line 74, in __setitem__
    self.tags[key] = value
  File "/home/user/streamripp/.venv/lib/python3.9/site-packages/mutagen/mp4/__init__.py", line 374, in __setitem__
    self._render(key, value)
  File "/home/user/streamripp/.venv/lib/python3.9/site-packages/mutagen/mp4/__init__.py", line 390, in _render
    return render_func(self, key, value, *render_args)
  File "/home/user/streamripp/.venv/lib/python3.9/site-packages/mutagen/mp4/__init__.py", line 789, in __render_cover
    b"data", struct.pack(">2I", imageformat, 0) + cover))
TypeError: can't concat Picture to bytes
```

**Comment by nathom** [comment] 2021-06-05 06:33
Closing because the issue doesn't reproduce.

**Closed by nathom** 2021-06-05 06:33 UTC
Labels: bug
